### ISSUE TITLE
[all]最新でないブラウザでアプリが正常に動作しない

### ISSUE THREAD

**Issue by hyoshie** [yshima42/ft_transcendence#279]
42vmの初期設定のブラウザで、正常に動作しませんでした。
動作環境：42vm

- chrome
  - version：Version 80.0.3987.162 (Official Build) (64-bit)
  - エラー：ログインすると401エラー
  - cookieがブラウザに保存されていなかった

- firefox
  - version：Mozilla Firefox 72.0.2
  - エラー：白いページが出て何も操作できない
  - 原因は未調査

**Comment by Masaya-Kamei** [comment]
最新のブラウザで動けば良さそう
