### ISSUE TITLE
[all, game]WebSocketのAuthGuard

### ISSUE THREAD

**Issue by kohkubo** [yshima42/ft_transcendence#285]

**Comment by Masaya-Kamei** [comment]
@kohkubo 
handleConnection で、guard の処理を直接書いてます。
@UseGuards(AuthGuard) を使ってない理由は、handleConnection には付けても、入ってくれなかったためです。
handleConnection のみに書いてる理由は、認証はdbアクセスするので、websocket で毎回やるのは、どうかと思ったためです。
