### ISSUE TITLE
[all] ソケットでエラーを返した場合のクライアントのエラーハンドリングをどうすればいいのか、やり方わかったら教えてほしいです。

### ISSUE THREAD

**Issue by Masaya-Kamei** [yshima42/ft_transcendence#292]
ソケットでエラーを返した場合のクライアントのエラーハンドリングをどうすればいいのか、やり方わかったら教えてほしいです。

_Originally posted by @kohkubo in https://github.com/yshima42/ft_transcendence/issues/265#issuecomment-1365696857_

**Comment by kohkubo** [comment]
結論わかったら教えてほしいです。
