### ISSUE TITLE
[game] ボールスピードが変。(normal が通常より早い)

### ISSUE THREAD

**Issue by Masaya-Kamei** [yshima42/ft_transcendence#298]
ボールスピードが変。(normal が通常より早い)。ボーススピード相手に通知

_Originally posted by @Masaya-Kamei in https://github.com/yshima42/ft_transcendence/issues/223#issuecomment-1371918722_

**Comment by yshima42** [comment]
ごめんなさい、slowを通常と一緒にしてしまってました。ミスです。

**Comment by yshima42** [comment]
https://github.com/yshima42/ft_transcendence/pull/223
こちらで修正しました。
