### ISSUE TITLE
[game] 招待中に招待された側がリロードすると、Reconnect がでる。

### ISSUE THREAD

**Issue by Masaya-Kamei** [yshima42/ft_transcendence#299]
招待中に招待された側がリロードすると、Reconnect がでる。

_Originally posted by @Masaya-Kamei in https://github.com/yshima42/ft_transcendence/issues/223#issuecomment-1371920253_

**Comment by yshima42** [comment]
https://github.com/yshima42/ft_transcendence/pull/223#issuecomment-1373011756
こちらも要修正。
