### ISSUE TITLE
[all] バッチいらない場合、UserAvatar 使わず、<LinkedAvatar link={link} src={avatarImageUrl} /> 使う！

### ISSUE THREAD

**Issue by Masaya-Kamei** [yshima42/ft_transcendence#302]
link は、自分の場合/app/profile 、それ以外は/app/users/:id
(これをLInkedAvatar 内でやろうとすると、api 叩くことになるので、呼び出し前にやる)

**Comment by Masaya-Kamei** [comment]
プロフィールページの左上と、Usersページのフレンドタブのユーザー一覧、サイドバー左下。

**Comment by hyoshie** [comment]
こちら、cypressのテストやる中で修正しました。
プルリク投げるまでお待ち下さい。
