### ISSUE TITLE
マイグレーションファイルをコミットしないようにする

### ISSUE THREAD

**Issue by kohkubo** [yshima42/ft_transcendence#319]
本番環境の再現のときは手前で必要なステップを手動もしくはシェルで実行するようにする。

**Comment by hyoshie** [comment]
こちら非機能要件にします。
理由は、
１．migrationファイルのヴァージョン管理することが公式で推奨されている
https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/team-development#source-control
２．本番環境での実行時にmigrationファイルを作るのは非合理的
