### ISSUE TITLE
[chat]チャットとDMでの名前の表示がニックネームになっていない

### ISSUE THREAD

**Issue by yshima42** [yshima42/ft_transcendence#336]
![Screen Shot 2023-01-10 at 11 19 21](https://user-images.githubusercontent.com/87764458/211447094-acbfc94f-206a-47b7-b155-d7333cb1ddbd.png)

基本的に名前表示はニックネームでするべきかと思います。もしよければこちらで修正することも可能です。

**Comment by kohkubo** [comment]
じゃあ、チャット周りのデザインの修正、お任せしようかな？

**Comment by yshima42** [comment]
#327 で既出でしたね。
