### ISSUE TITLE
ウェブサイトはSQLインジェクションから保護されなければならない?

### ISSUE THREAD

**Issue by yshima42** [yshima42/ft_transcendence#347]

**Comment by hyoshie** [comment]
[Raw database access \(Reference\)](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#sql-injection)
[SQLインジェクションへの対策｜国民のためのサイバーセキュリティサイト](https://www.soumu.go.jp/main_sosiki/cybersecurity/kokumin/business/business_admin_06.html)
