### ISSUE TITLE
チャット機能の実装

### ISSUE THREAD

**Issue by yshima42** [yshima42/ft_transcendence#53]
## あるべき
- [ ] NestJSのWebsocketが理解できて使える
- [ ] 参考にするべきAPIが複数見つかっている
- [ ] APIとして提供する機能リスト化できている
- [ ] ER図が書けている(プロトタイプレベル)
- [ ] シンプルな一つのチャットルームができている(ブラウザ操作orPostmanテスト)

## やること
- [x] サブジェクトの確認
- [ ] [socket.ioのチュートリアル](https://socket.io/get-started/chat)
- [ ] [Build a real\-time chat application with Nestjs and PostgreSQL](https://arctype.com/blog/postgres-nestjs/)

### 最優先
- シンプルな一つのチャットルームを作る→拡張する
### 後回し
- チャットルーム
- DM
- ブロック機能
- チャンネルオーナー概念
	- パスワード
- チャンネル管理者概念
- Pongゲームに招待する機能
- プロフィールにアクセスする機能

## サブジェクト
>II.4 チャット
>ユーザーのためのチャットも作成する必要があります。
>- ユーザーはチャンネル(チャットルーム)を作成できる必要があります。
>チェンネルは、公開、非公開、パスワードで保護することができます。
>- ユーザーは、他のユーザーにダイレクトメッセージを送ることができる必要があります。
>- ユーザーは、他のユーザーをブロックすることができます。
>この方法では、ブロックしたアカウントからのメッセージは見えなくなります。
>- 新しいチャネルを作成したユーザーは、そのチャネルを離れるまで自動的にチャネルオーナーに設定されます。
>チャンネルの所有者は、チャンネルにアクセスするために必要なパスワードを設定したり、変更したり、削除したりすることができます。
>- チャンネル所有者はチャンネル管理者です。他のユーザーを管理者として設定することができます。
>チャンネルの管理者は、ユーザーを一定期間禁止したり、ミュートすることができます。
>- ユーザーは、チャットインターフェースを通じて、他のユーザーをPongゲームに招待できる必要があります。
>- ユーザーは、チャットインターフェイスを通じて、他のプレーヤーのプロフィールにアクセスできる必要があります。

**Comment by kohkubo** [comment]
## Chat MVP

### DM

- DM一覧が表示できる(実質Friend一覧)
- DM一覧から個別のDM画面に遷移できる
- メッセージ一覧が見える
- メッセージが送れる
- メッセージが受け取れる(リアルタイムではなく更新したときに反映できればOK

### Chat

基本的にチャットルームの作成機能以外はロジックは使い回せる。

- チャットルームが作成できる
- チャットルーム一覧が表示できる
- チャットルームに入室できる
- メッセージ一覧が見れる
- チャットルームでメッセージが送れる
- メッセージが受け取れる(リアルタイムではなく更新したときに反映できればOK

**Comment by yshima42** [comment]
細かく書いてあって良いですね。
一点だけ、めちゃ迷いどころだと思うのですが、リアルタイムチャットをMVPで実装するかどうかについて明日(11/30)10分ほどでもお話できたら嬉しいです。(MVPでは実装しない選択はとてもありだと思ってます。ゲーム側との兼ね合いも合わせて認識合わせしておきたく。)

**Comment by yshima42** [comment]
機能要件の実装は完了済み。
#212 追加要件のissueにてチャット機能は管理するためクローズ。
