### ISSUE TITLE
[MVP] 環境整備

### ISSUE THREAD

**Issue by Masaya-Kamei** [yshima42/ft_transcendence#73]
＊＊修正前＊＊
番号は優先順位

1. env/main-check ブランチ
   - [ ] pre-push 時に、main とのコンフリクトをチェック (取り込み忘れをチェック)
   - [ ] main へのマージをdiscord 通知。

2. env/hooks ブランチ
   - [ ] frontend srcs/ 直下に、エンドポイントごとのhooks 作る。

3. env/github-actions ブランチ
   - [ ] github actions で自動テスト(DB接続もする)

4. env/frontend-test ブランチ
   - [ ] e2e テスト 全ページにアクセスしてページが表示されているか。
   - [ ] 統合テスト エラーハンドリングできているか。
   - [ ] 他に何をテストするべきか考える。

5. env/docker-compose ブランチ
   - [ ] docker-compose up で全起動

**Comment by yshima42** [comment]
MVPとしての修正案です。明日(11/30)お話ししましょう。

【MVPでやること】(優先順位順)
- main へのマージをdiscord 通知
- github actions で自動テスト(DB接続もする)
- docker-compose upで全起動
- frontend srcs/ 直下に、エンドポイントごとのhooks 作る（すぐできるのであればやる）

【機能要件の部分でやること】
-  e2e テスト 全ページにアクセスしてページが表示されているか
- 統合テスト エラーハンドリングできているか
- 他に何をテストするべきか考える

【修正案理由】
判断基準は、「今これをやることが、1週間後にMVPを完成させる上でチャットやゲームよりも優先度が高いのかどうか」での修正案です。判断間違っている部分もあると思うので話しましょう。

**Comment by Masaya-Kamei** [comment]
修正後
番号は優先順位

1. env/main-check ブランチ
   - [x] #113
   - [ ] #114

2. env/hooks ブランチ
   - [ ] #115

3. env/frontend-test ブランチ
   - [ ] e2e テスト 全ページにアクセスしてページが表示されているか。

4. env/github-actions ブランチ
   - [ ] github actions で自動テスト(DB接続もする)

5. env/docker-compose ブランチ
   - [ ] docker-compose up で全起動

**Comment by yshima42** [comment]
#118 にて切り出し。その他は終わっているためクローズ。
