### ISSUE TITLE
[機能要件] ユーザーアカウント

### ISSUE THREAD

**Issue by hyoshie** [yshima42/ft_transcendence#85]
### 1. フレンド関連の機能
- [x] フレンドを追加できる
- [x] フレンド一覧を表示できる
- [x] #166
現在の状態は、online、 offline,、in a gameのいずれかである

### 2. プロフィール関連の機能
- [x] 自分のプロフィールを表示できる
- [x] 任意のユーザーのプロフィールを表示できる
- [x] ユーザーのアイコン画像をクリックすると、そのユーザーのプロフィールに遷移する
- [x] ユーザー名を変更できる
- [x] デフォルトのプロフィール画像（アバター）が設定されている
- [x] プロフィール画像（アバター）を変更できる
- [x] プロフィール画像（アバター）をアップロードできる
- [x] デフォルトのプロフィール画像（アバター）が設定されている
- [x] ユーザーが二要素認証を有効にできる
#### プロフィール情報一覧
- ユーザー名
- プロフィール画像
- ゲームの統計情報
勝敗数、ラダー（レベル）
- ゲームの対戦履歴
対戦相手、スコア、勝敗、自分と対戦相手のラダー（レベル）

### 3.その他の機能
- [x] 42intraのOAuthシステムを使用してログインできる
- [x] 二要素認証を使用してログインできる
- [x] #167
サブジェクトではチャットの欄に記載されているが、現状ユーザーの情報として管理している

**Comment by hyoshie** [comment]
機能要件では、ゲームの統計情報に実績を含めなくてよいと認識しています。

**Comment by yshima42** [comment]
実装済み
